### ISSUE TITLE
[Help Wanted] [Heroku deployment] use process.env.PORT

### ISSUE THREAD

**Issue by aaayushsingh** [Polymer/pwa-starter-kit#116]
The server runs on port 8080, 8081 and 3000 depending on the kind of build and ignores process.env.PORT on Heroku.

How to deploy this on Heroku after building?

**Comment by Dabolus** [comment]
Hi, where did you insert the `--port $port` argument? Inside the `package.json` or directly when calling the script? (e.g. `npm start --port $port`)

**Comment by Dabolus** [comment]
@aaayushsingh yes it does, because passing the `--port $PORT` argument directly when calling the script won't actually work, as the argument won't be given to the command the script runs. For example, calling:
```
npm start --port $PORT
```
Won't pass the port argument to `polymer serve`. In this case you would need to call
```
npm start -- --port $PORT
```

That extra `--` will allow you to pass additional argument to the command that is called by the script.
By the way, since you wrote the argument directly inside `package.json`, this is not your case

**Comment by notwaldorf** [comment]
As the instructions say, you can pass the port to the the `npm start` script:
<img width="761" alt="screen shot 2018-05-18 at 11 59 02 am" src="https://user-images.githubusercontent.com/1369170/40252964-e315af4e-5a92-11e8-9a21-54024c0ca872.png">

**Comment by aaayushsingh** [comment]
@notwaldorf That doesn't work. I've tried that and I've also tried adding port directly in the start script. Didn't work either. 

When pulling Heroku logs, it says failed to bind port.
