### ISSUE TITLE
New views/section directory

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#123]
What do you think about a `views` directory for the components views:

* `my-view1.js`
* `my-view2.js`
* `my-view3.js`
* `my-view404.js`

I don't care so much about the name (views/sections/pages/etc) but about the concept.

| From | To |
|------|----|
| ![before](https://user-images.githubusercontent.com/1007051/40555368-1eb3d830-6049-11e8-8989-c1527fb25cc5.png) | ![after](https://user-images.githubusercontent.com/1007051/40555370-211a84fc-6049-11e8-9e9e-98b43f04c12d.png) |

**Comment by notwaldorf** [comment]
I think we may have considered this at a point, but the difference between "views" and "components" was a bit muddy. All views are components; should you put `page-view-element.js` in `/views`? it's only used by the views. Should you put like styles only used by the views in there?

I'm not opposed to this change (i love subfolders), but @frankiefu @keanulee wdyt?

**Comment by abdonrd** [comment]
Yes, I'm also not sure what would be the best way. That's why I wanted to throw the question openly. 🙂

**Comment by notwaldorf** [comment]
I thiiiink that this is going into very app specific details, and for a template opens a can of worms because of the grey area questions I asked above. I added a [sentence in the wiki](https://github.com/Polymer/pwa-starter-kit/wiki/3.-Configuring-and-personalizing#folder-structure) explaining that you can create these folders in _your_ app, but won't adding them for now to the template. Hope that's ok!
