### ISSUE TITLE
Chrome on iOS displays a blank screen

### ISSUE THREAD

**Issue by shawnnosaurus** [Polymer/pwa-starter-kit#181]
I really want this project to work for my team, but our company will never accept without a wide support list. I would love to be able to give more detail on this, but I don't know of a good way to debug chrome on iOS. 
**Device:** iPhone 5S
**iOS Version:** 9.0
**Chrome Version:** 62.0.3202.70

**Comment by keanulee** [comment]
iOS 9 [doesn't support ES2015 features](https://github.com/Polymer/tools/blob/master/packages/browser-capabilities/src/browser-capabilities.ts#L78), but prpl-server thinks it's Chrome so it serves the `/es6-bundled` build which is a mistake. The [static build](https://static-dot-pwa-starter-kit.appspot.com/) (which is `/es5-bundled`) should work fine.

This is related to how prpl-server thinks Chrome 64+ on iOS <11.3 [supports ES modules](https://github.com/Polymer/tools/blob/master/packages/browser-capabilities/src/browser-capabilities.ts#L45) so it serves the `/esm-bundled/` build (which, because iOS Chrome uses the WebKit engine, doesn't actually support modules).

cc @aomarks

**Comment by shawnnosaurus** [comment]
Awesome that makes sense, thanks for such an ensiteful and fast response. In my case, I might then have to forgo the detection completely and just serve the es5 version across the board. I will still log this to the prpl-server project for visibility, if it's not there already, thanks again.

**Comment by aomarks** [comment]
I started https://github.com/Polymer/tools/pull/555 to add special handling for Chrome on iOS to browser-capabilities and prpl-server.

**Comment by shawnnosaurus** [comment]
Thanks so much, you don't know how much this project means to the future of mine and my teams careers. Keep up the great work, weather you see it or not, you all are making an impact in people's lives around the world.
