### ISSUE TITLE
<iron-ajax> or 'fetch'?

### ISSUE THREAD

**Issue by andreabioli** [Polymer/pwa-starter-kit#185]
I know that probably there cannot be any 'definitive' solution, but it would be helpful at least have some thoughts on this, as a general approach to develop an application in 'Polymer + Redux'...

**Comment by askbeka** [comment]
I'd say better approach for building apps using any component based library is to treat component as pure functions in FP. No side effects. And having requests in component means side effects. You can have different output for the same input to your component depending on response and time it took.
But if you think of it differently, since form elements also have side effects (user input), you can treat some components as source of side effects, and use them to read data from rather than controlling their output, thats how most apps in Polymer are built. But since Redux is one directional data flow and and it was built with React in mind, which is all about functinal programming and purity, It expects you to have pure components, and there are options like redux-saga that can help you with that.
So conclusion is to do requests outside of components if you use redux, so iron-ajax is abd choice.
Redux and Polymer do not play nice together. You will have lots of pain trying to combine Reduxs purity and Polymers DOM centric approach.

**Comment by andreabioli** [comment]
Thank you for your perfectly motivated answer... but now this opens up just the problem you mentioned at the end of your message: probably Polymer and Redux don't fit very well together.
I didn't want to say it explicitly, but having worked before in a complex React/Redux application, I can see the giant differences in the approach.
We should then ask the creators of this PWA Starter Kit (that probably are not so far away from the creators of Polymer) what is the intent, with this 'appetizer'... :-)
What are the suggested directions for future development??? I know that the easy answer is 'do whatever you want, we support everything', but maybe there could be something more elaborated than this...

**Comment by keanulee** [comment]
We don't use iron-ajax in PWA Starter Kit, but rather fetch() statements in actions (not PWA Starter Kit specifically, but the templates we updated based on it like [Shop](https://github.com/Polymer/shop/blob/lit-element/src/actions/categories.js#L62) and [HN](https://github.com/PolymerLabs/polymer-redux-hn/blob/master/src/actions/lists.js#L17)). We're trying not to be too prescriptive about data flow, but the concept of lit-html/LitElement definitely lends itself more to rendering purely based on property values (which is what we try to do here with a basic Redux setup). PolymerElement had features like two-way data-binding (which isn't very Redux-compatible), but one could still write PolymerElements that render purely based on properties and dispatch actions on events instead of "notifying up the tree".

**Comment by notwaldorf** [comment]
(the [no-redux](https://github.com/Polymer/pwa-starter-kit/tree/template-no-redux) branch of this repo does something similar, dispatching events and rendering purely based on properties)

**Comment by andreabioli** [comment]
Thanks again, both, for your insights (interesting the 'no-redux' branch, by the way, to get some other idea...).
If this is trend, I don't see a bright future, for <iron-ajax> :-)

**Comment by keanulee** [comment]
In a world with `fetch()`, it's so easy to write JS that I would encourage users to use that instead of iron-ajax.
