### ISSUE TITLE
JS bundles in the 'esm-bundled' build are downloaded twice

### ISSUE THREAD

**Issue by vlukashov** [Polymer/pwa-starter-kit#191]
As a developer I want to use the push manifest to push JavaScript modules to the browser and expect the pushed files to be used when the browser encounters a `<script type="module">` tag or a dynamic `import()` directive later on the page.

I do not expect that the browser would download the pushed files multiple times during the same page load. Yet, this is what happens currently in the `esm-bundled` build:

![es-module-duplicate-download-with-http2-push](https://user-images.githubusercontent.com/22416150/42569089-13a6b572-8518-11e8-9356-49a84f96a8c4.png)
This behavior can be observed at [pwa-starter-kit.appspot.com](https://pwa-starter-kit.appspot.com/) (open in a browser that supports ES modules).

The likely reason for the issue is that the _credentials mode_ of the pushed resources does not match that of the ES modules used on the page. That causes the browser to ignore the pushed copies and download the same files again but with a different credentials mode (see details [here](https://developers.google.com/web/updates/2017/12/modulepreload#ok_so_why_doesnt_link_relpreload_work_for_modules)).

To me this issue looks like something to be fixed in `prpl-server` rather than in the PWA starter kit (see https://github.com/Polymer/prpl-server-node/issues/81). But until it is fixed, I would expect the PWA starter kit to disable HTTP resource hints for the `esm-bundled` build because they seem to make the performance worse, not better:

<img width="1368" alt="push-manifest-slows-first-page-load" src="https://user-images.githubusercontent.com/22416150/42593414-04680b0a-8555-11e8-900c-1d5f62a045c9.png">

**Comment by frankiefu** [comment]
Push in esm-bundled build does make loading faster. The 2nd request for the same JS modules should be hitting the disk cache since the resource is already pushed. In your test I think if you uncheck "Disable cache" in dev tools you should see the expected results. A better test would be running it on webpagetest which simulates a more real world environment. Here is the waterfall result: https://www.webpagetest.org/video/compare.php?tests=180712_AN_147c9f45bfda76453c0b9a6fe1633bb2-r%3A3-c%3A0&thumbSize=200&ival=100&end=visual

![waterfall](https://user-images.githubusercontent.com/116360/42650000-12851352-85c0-11e8-8c7b-8a40828f3c43.png)


Ideally the 2nd request shouldn't even happen and I think it's due to the fact that we use `rel=preload` instead of `rel=modulepreload` to workaround GAE not supporting `rel=modulepreload`. It's possible adding `crossorigin` may help but I am not sure. @keanulee has done some work around this subject and can provide more insights when he is back from vacation next week.

cc @aomarks

**Comment by vlukashov** [comment]
Indeed, the 'disable cache' setting in the Chrome DevTools was on, and that has affected the measurements. Thanks for pointing that out! When cache is working normally, pushing resources gives a performance improvement on my machine as well.

The issue is really not as bad as it initially appeared: even though resources are pushed with wrong headers, the browser seems to handle this case correctly anyways.

But it is still there: both Chrome and Safari do show warnings in the console saying that the pushed resources were never used:

![chrome-push-warnings](https://user-images.githubusercontent.com/22416150/42681181-a7036e78-868f-11e8-8de2-2250537a2848.png)
![safari-push-warnings](https://user-images.githubusercontent.com/22416150/42681182-a71f5caa-868f-11e8-8f55-aa4d7bee7831.png)

That is, the browsers are with you on that the second request should never happen at all. It would be nice to get rid of these warnings.

However, if this does not seem to have real adverse performance implications on the PWA starter kit, I let you decide whether or not you want to keep this issue open. I think that for `prpl-server` it is still valid and needs to be fixed, but there is [another ticket](https://github.com/Polymer/prpl-server-node/issues/81) to track that.

**Comment by frankiefu** [comment]
It seems a valid request to support `crossorigin` mode in the link headers in prpl-server. Closing this in favor of the other [issue](https://github.com/Polymer/prpl-server-node/issues/81).
