### ISSUE TITLE
Provide a template with TypeScript

### ISSUE THREAD

**Issue by frankiefu** [Polymer/pwa-starter-kit#232]

**Comment by Dabolus** [comment]
Would love to help with this one! Would it be possible to do it just using the Polymer CLI, though?

**Comment by eterna2** [comment]
@frankiefu 
Hi, I actually finished converting it to typescript in my own [fork](https://github.com/e2forks/pwa-starter-kit/tree/template-typescript). 

**Some major changes**
- Updated lit-element to 0.6, polymer-cli to 1.8, puppeteer to 1.5 (with the relevant updates for the changes in lit-element)
- Added custom type-definitions for the pwa-helpers (probably be making a PR for pwa-helpers)
- Fix the visual test to wait for the lazily loaded view to load (via waitForFunction)

**Comment by keanulee** [comment]
I'm inclined to keep working on #235. The PR is marked as [do not merge] because we intend to keep it as a template (like the other `template-minimal-ui`, etc. templates), but it should have up to date dependencies (pwa-helpers, lit-element, polymer-cli, puppeteer, etc.). Note that package.json only specifies _minimum_ semver versions - the actual installed version is higher in package-lock.json/when you run `npm i`. If there's anything I'm missing I'd accept PRs on the `typescript` branch.

**Comment by eterna2** [comment]
@mercmobily

I think #235 is doing great. 

I made the fork cuz I need to building something right now and it wasn't ready then.

But the present #235 is pretty neat. It is almost the same as my fork. And they have updated with the new `pwa-helpers` which is in typescript. 

My fork is still using the old version with my custom written type definitions. So it is better to use #235. I updated my app but not my fork.

The only difference is I did not use `ActionCreator` because the args type is `...args: any[]` which make u lose the type check when u try to create an action.

I created my own variant of `ActionCreator` and `ThunkActionCreator` to which keeps the typings. (Not updated in my fork, but I did that for my app)..

Otherwise we r almost identical. I will drop by make a PR and see whether they think this a better approach.

**Comment by mercmobily** [comment]
I guess this issue can be closed...?

**Comment by mercmobily** [comment]
(Thank you for your work @eterna2 !

**Comment by keanulee** [comment]
#235 merged. TypeScript template now available on `template-typescript` branch.
