### ISSUE TITLE
[Feature Request] template that uses webpack

### ISSUE THREAD

**Issue by goatandsheep** [Polymer/pwa-starter-kit#272]
Can we get a template that uses webpack? I'm really struggling to get some of the npm packages to work because they're not all written as es modules

**Comment by Dabolus** [comment]
Some months ago I started working on a Webpack version of this Starter Kit. Since I noticed that many people are actually looking for this, yesterday I decided to go on with it. It is still not completely perfect (for example, tests are still missing), but it's working and it already supports multi builds to be used with PRPL Server. If you're interested, check it out [here](https://github.com/Dabolus/pwa-webpack-starter-kit).

**Comment by goatandsheep** [comment]
Awesome!! This is amazing!

**Comment by lkraav** [comment]
@goatandsheep you could also check out https://github.com/web-padawan/polymer3-webpack-starter this high quality work
