### ISSUE TITLE
Different Webpack Build and Polymer Build on Branch Webpack ?

### ISSUE THREAD

**Issue by muhammadridho** [Polymer/pwa-starter-kit#355]
Can you describe what the different about polymer build and webpack build ? ,  is it same, so why just not on webpack build , because i think the concern is webpack on that branch.

**Comment by keanulee** [comment]
We use `polymer build` by default in pwa-starter-kit because it supports multiple builds for different browser capabilities out-of-the-box, and thus it is the recommended approach. However, `polymer build` doesn't support certain packages that don't distribute as ES modules, so some users have asked for how to use alternative build tools - we maintain the separate `webpack` branch to show how to do this.

Ref #272
