### ISSUE TITLE
Update to Redux v4

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit#76]
https://github.com/reactjs/redux/releases/tag/v4.0.0

**Comment by notwaldorf** [comment]
@abdonrd I haven't looked much into Redux 4 -- do you expect this to be just a dependency update, or to actually require code changes?

**Comment by frankiefu** [comment]
There is an issue with `redux-devtools-extension` + `Redux v4`: https://github.com/reactjs/redux/issues/2943

 Because of that and maybe other compatibility issues [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) also hasn't updated to Redux v4 yet.

**Comment by Dabolus** [comment]
Ok so, looking at [Redux 4 breaking changes](https://github.com/reactjs/redux/issues/1342), it seems like nothing will affect this project. To test this out, I tried to clone the repo and simply update the redux dependency. As @frankiefu already said, redux devtools will break everything, but in an incognito window everything kept working like a charm, so I can confirm that besides the devtools extension problem, updating to Redux 4 does not require any changes in the code. The great thing is that Redux 4 does not depend on lodash anymore, so we will save a lot of extra bytes too (and it is also  [much faster!](https://github.com/reactjs/redux/pull/2599))

**Comment by abdonrd** [comment]
@notwaldorf with the comments of @frankiefu and @Dabolus, I have nothing more to say! 😁

**Comment by Dabolus** [comment]
Small update: seems like `redux-devtools-extension` has been abandoned 😕

**Comment by ashrafhadden** [comment]
@notwaldorf @frankiefu I think the incompatibility issue just got resolved?
- https://github.com/zalmoxisus/redux-devtools-extension/commit/7db8972831def77e45b6c98b15911a77cbd3ff93
- https://github.com/zalmoxisus/redux-devtools-extension/issues/499#event-1691423921

Someone should test it out! Apparently, it right now only works from manually installing latest npm package: [see last comment](https://github.com/zalmoxisus/redux-devtools-extension/pull/490)

@Dabolus [9 new commits](https://github.com/zalmoxisus/redux-devtools-extension/commits/master) 🌱since June 15th, so it looks like the [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension) repo was brought back to life! :relaxed:
