### ISSUE TITLE
[DISSCUSION] Why not use js for the only attached the views active

### ISSUE THREAD

**Issue by Borjagodoy** [Polymer/pwa-starter-kit#82]
Hi!

In the [my-app](https://github.com/Polymer/pwa-starter-kit/blob/8639bd331bd388211f80a14671ec156bab120444/src/components/my-app.js#L89) file, has been replaced the iron-page by main tag and the attribute active in the views. That is good because lit html help us to manage the render of the inactives views but doesn't detached the components from the DOM.

The problem for example, is when we have a  _stateChanged method on inactive views. This method will be call even if the view is inactive, because lit html doesn't control the call to _stateChanged method. It Also happens with listeners attached to the document inside the inactive views.

A possible solution could be using js to control the render of  inactive views, removing these views  from the DOM. 

```javascript 
    <main class="main-content">
      ${this.getPage(_page)}
    </main>

     ...

      getPage(_page) {
    switch(_page) {
      case 'view1':
        return html`<my-view1 class="page" active></my-view1>`
        break;
      case 'view2':
        return html`<my-view2 class="page" active></my-view2>`
        break;
      case 'view3':
        return html`<my-view3 class="page" active></my-view3>`
        break
      case 'view404':
        return html`<my-view404 class="page" active></my-view404>`
        break
      default:
        return html`<my-view1 class="page" active></my-view1>`
    }  
```

This will give us more control on all listeners inside the views by disconectCallback method . But I'm not sure about the posible impact in performance.

**Comment by notwaldorf** [comment]
Even though the `_stateChanged` method gets called for inactive views, we've prevented it from calling render, which is the expensive part -- this is done by the `PageViewElement` base class (see docs: https://github.com/Polymer/pwa-starter-kit/wiki/3.-Configuring-and-personalizing#conditionally-rendering-views)

We didn't want to throw away the DOM when switching pages because if your view is really heavy and expensive to create, you will have to re-pay this cost every time you have to switch back to it (and recreating DOM is usually way more expensive that running some JS setters). As a result, we wanted to keep the work you've already done creating that DOM, and just make sure the view is frozen/inactive. This is especially important for a template, where we wanted to have the good, performant pattern out of the box, and to give you the option to deviate from it if you really know what you're doing.

If you're confident your views are small and cheap to create, you can totally do exactly what you're saying!
