### ISSUE TITLE
[PROPOSAL] pwa-starter-kit as a github-fetch-starter template.

### ISSUE THREAD

**Issue by vdegenne** [Polymer/pwa-starter-kit#92]
Recently I've made [github-fetch-starter](https://github.com/vdegenne/github-fetch-starter), a micro node app that lets you fetch a "starter" release on github. There are few advantages to use this program compared to a barbarian "`git clone` all my starter" : 

- You can control which files are included in the starter. `.git`, `.travis.yml`, and other files are usually not intended to be on the end-user file-system.
- You don't want your end-user `git clone` the master state of your project because it could have a failure build state.
- `github-fetch-starter` implements a dummy placeholder replacement system. A template is like a mold with customizable parts, these variable parts are user-dependent (e.g. `application name`, `description`, etc...). `github-fetch-starter` prompts for every placeholders found in the starter during fetch time. As soon as the starter is made available on the user file-system, the user does not need to brain consume what tiny parts are customizables and can directly focus on writing components.

I originally made this application for personal use but I love Polymer and your decision to make it available in the `node` empire was more than appreciated. Therefore I thought this tool of mine could be of use for you. And it was made with love.

*(Feel free to contact me or to PR the repository in case you are interested or want to see some changes)*

**Comment by notwaldorf** [comment]
Hiya! Thanks for the proposal! I think the plan is to integrate this in the `polymer-cli`, so that you can do `polymer init pwa-starter-kit`, but the team hasn't had a chance to get that working. For now, I don't think we want to use any instructions that use more third party apps, since we're trying to keep this as simple for beginners, but I did update the command to use `git clone --depth 1`, so that at least you're not getting all of my garbage commits when you clone 😅
