### ISSUE TITLE
build script only supports mac

### ISSUE THREAD

**Issue by ralcar** [Polymer/pwa-starter-kit#95]
npm run build currently builds prpl-server & static, but as a windows user the prpl-server script does not work, since it uses commands like:
rm -rf
mv
renamer

none of these commands work on windows. Not really hard to change as a windows users, but perhaps should work out of the box?

**Comment by Dabolus** [comment]
I can work on this one. @notwaldorf how should this be handled? Maybe using a task runner or a simple node script?

**Comment by keanulee** [comment]
The `build:static` command should work on Windows because it's just `polymer build`. The `build:prpl-server` command does a few things:

1. `polymer build --auto-base-path` to set the base path for each build (for prpl-server). This should work on Windows.
1. `rm -rf ...`/`mv ...` to move the build output directory to server/, which contains configuration files for deploying to App Engine. They can be replaced by equivalent commands in Windows.
1. `rename ...`/`replace ...` to rename directories and references of node_modules/ to node_assets/. This hack is needed because of a peculiarity of App Engine which doesn't upload any directories (and subdirectories) that contain "node_modules". This step may not be necessary with other hosting services.

Perhaps the best way forward is to write a gulp script that handles these steps in a cross-platform way.

**Comment by keanulee** [comment]
@Dabolus do you want to take a try at this? It doesn't necessarily need to be gulp - whatever is simplest is best.

**Comment by Dabolus** [comment]
Yep, I will be working on adding some basic gulp integration tomorrow morning, you can assign this to me if you want.
